# Generated by Django 3.2.12 on 2023-03-11 03:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0004_auto_20230310_1021'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='decription',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
    ]
